/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.prokarma.pkmst.controller;

import com.prokarma.pkmst.model.PaymentDetails;
import com.prokarma.pkmst.model.PaymentOutput;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;

import java.util.List;
/**
 * Provides the info about api methods
 * @author pkmst
 *
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaPKMSTServerCodegen", date = "2022-06-01T16:46:40.877Z")

@Api(value = "Payments", description = "the Payments API")
public interface PaymentsApi {

    @ApiOperation(value = "Process a payment", notes = "", response = PaymentOutput.class, authorizations = {
        @Authorization(value = "ApiKeyAuth")
    }, tags={ "payments", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful payment", response = PaymentOutput.class),
        @ApiResponse(code = 400, message = "Invalid payment"),
        @ApiResponse(code = 401, message = "Not authenticated") })
    @RequestMapping(value = "/payments/credit-card",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<PaymentOutput> paymentsCreditCardPost(@ApiParam(value = "" ,required=true )   @RequestBody PaymentDetails body, @RequestHeader(value = "Accept", required = false) String accept) throws Exception;

}
