/*
 * Payment API
 * Payment system
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.prokarma.pkmst.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.prokarma.pkmst.model.PaymentDetails;
import com.prokarma.pkmst.model.PaymentOutput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.http.ResponseEntity;
import org.springframework.web.multipart.MultipartFile;

/**
 * API tests for PaymentsApi
 */
@Ignore
public class PaymentsApiTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    private final PaymentsApi api = new PaymentsApiController(objectMapper);

    private final String accept = "application/json";

    
    /**
     * Process a payment
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void paymentsCreditCardPostTest() throws Exception {
        PaymentDetails body = null;
    ResponseEntity<PaymentOutput> response = api.paymentsCreditCardPost(body , accept);

        // TODO: test validations
    }
    
}
